services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_USER=k6
      - INFLUXDB_PASSWORD=k6pass

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb

  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./tests:/scripts/tests
      - ./.env:/scripts/.env
    env_file:
      - .env
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
      - TEST_FILE=${TEST_FILE:-loadtest.js}
      - API_URL=${API_URL:-http://localhost:8080}
      - VUS=${VUS:-10}
      - DURATION=${DURATION:-30s}
    depends_on:
      - influxdb
    command: ["run", "/scripts/tests/${TEST_FILE:-loadtest.js}"]
